# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
# 4,000,000
#
# val1=1
# sum=0
# val2=2
# val3=val1+val2
# val4=val2+val3
# while val3<4000000:
#     if val3%2==0:

a=1;b=2
sum=0;tmp=0;total=2;val=4000000
while sum<=val:
    sum=a+b
    a=b
    b=sum
    if sum>val:
        break
    if sum%2==0:
        total=total+sum
    # print(sum)

print(total)



